---
name: "AWS Network Configuration Survey"
description: "Survey to configure aws network Rresources to create an EC2 instance"
spec:
  - type: "text"
    question_name: "AWS region"
    question_description: "The AWS region where the resources should be created."
    variable: "region"
    required: true

  - type: "text"
    question_name: "VPC name"
    question_description: "The name of the VPC to create."
    variable: "vpc_name"
    required: true

  - type: "text"
    question_name: "VPC CIDR block"
    question_description: "The CIDR block to use for the VPC being created."
    variable: "vpc_cidr"
    required: true

  - type: "text"
    question_name: "Subnet CIDR block"
    question_description: "The CIDR block to use for subnet being created."
    variable: "subnet"
    required: true

  - type: "text"
    question_name: "Internal Security Group name"
    question_description: "The name of the security group to create."
    variable: "security_group_internal_name"
    required: true

  - type: "text"
    question_name: "Internal Security Group description"
    question_description: "The name of the security group to create."
    variable: "security_group_internal_description"
    required: true

  - type: "text"
    question_name: "Dict of Internal Security Group rules, seperated by semi colon"
    question_description: 'Dictionaries of Security Group Rules. e.g. {"proto": "tcp", "ports": "22", "cidr_ip": "10.1.1.0/16"}; {"proto": "tcp", "ports": "8000-8010", "cidr_ip": "10.1.1.0/16"}'
    variable: "security_group_rules"
    required: false
