---
argument_specs:
  main:
    short_description: Creation/Deletion of transit gateway with vpc/vpn attachment
    options:
      action:
        description: Action to be done
        type: "str"
        default: "create"
        choices: ["create", "delete"]
      transit_gateway:
        description: Transit Gateway to be created
        type: dict
        required: True
      vpc_attachment:
        description: VPC to be attached
        type: list
