---
- name: Terminate EC2 instance
  amazon.aws.ec2_instance:
    region: "{{ ec2_instance_create_aws_region }}"
    name: "{{ ec2_instance_create_instance_name }}"
    instance_type: "{{ ec2_instance_create_instance_type }}"
    image_id: "{{ ec2_instance_create_ami_id }}"
    key_name: "{{ ec2_instance_create_key_name }}"
    vpc_subnet_id: "{{ ec2_instance_create_vpc_subnet_id }}"
    security_group: "{{ ec2_instance_create_external_sg_id | default(omit) }}"
    tags: "{{ ec2_instance_create_tags | default(omit) }}"
    wait: "{{ ec2_instance_create_wait_for_boot }}"
    state: absent

- name: Delete security group if created
  amazon.aws.ec2_security_group:
    name: "{{ ec2_instance_create_external_sg_name | default('ec2_instance_create-default-external-sg') }}"
    state: absent

- name: Detach and delete Internet Gateway if created
  amazon.aws.ec2_vpc_igw:
    region: "{{ ec2_instance_create_aws_region }}"
    vpc_id: "{{ ec2_instance_create_vpc_id }}"
    state: absent
