---
- name: Run 'create_rds_global_cluster' role
  module_defaults:
    group/aws: "{{ aws_setup_credentials__output }}"

  block:
    - name: Include file
      ansible.builtin.include_tasks: "{{ create_rds_global_cluster_operation }}.yml"
