---
argument_specs:
  main:
    short_description: A role to create an EC2 instance with optional networking resources.
    description:
      - A role to create an EC2 instance.
      - Optionally can create a security group and associate an Elastic IP with the instance.
      - Supports custom configurations for instance settings, including instance type, AMI, key pair, tags, VPC/subnet, and networking configurations.
    options:
      ec2_instance_create_aws_region:
        description:
          - The AWS region in which to create the EC2 instance.
        required: true
        type: str
      ec2_instance_create_instance_name:
        description:
          - The name of the EC2 instance to be created.
        required: true
        type: str
      ec2_instance_create_instance_type:
        description:
          - The instance type for the EC2 instance.
        required: true
        type: str
      ec2_instance_create_ami_id:
        description:
          - The AMI ID for the EC2 instance.
        required: true
        type: str
      ec2_instance_create_key_name:
        description:
          - The name of the key pair to use for SSH access to the EC2 instance.
        required: true
        type: str
      ec2_instance_create_vpc_subnet_id:
        description:
          - The ID of the VPC subnet in which the instance will be launched.
        required: true
        type: str
      ec2_instance_create_tags:
        description:
          - A dictionary of tags to assign to the EC2 instance.
        required: false
        type: dict
      ec2_instance_create_wait_for_boot:
        description:
          - Whether to wait for the EC2 instance to be in the running state before continuing.
        required: false
        default: true
        type: bool
      ec2_instance_create_associate_eip:
        description:
          - Whether to create and associate an Elastic IP (EIP) with the EC2 instance.
        required: false
        default: false
        type: bool
      ec2_instance_create_associate_external_sg:
        description:
          - Whether to create and associate a security group for external access.
        required: false
        default: false
        type: bool
      ec2_instance_create_external_sg_name:
        description:
          - The name of the security group to create.
        required: false
        default: "ec2_instance_create-default-external-sg"
        type: str
      ec2_instance_create_external_sg_description:
        description:
          - A description of the security group.
        required: false
        default: "Security group for external access"
        type: str
      ec2_instance_create_sg_tags:
        description:
          - Tags to assign to the security group.
        required: false
        type: dict
      ec2_instance_create_associate_igw:
        description:
          - Whether to create and associate a internal gateway.
        required: false
        default: false
        type: bool
