---
- name: Deploy resource from Bastion
  delegate_to: bastion
  module_defaults:
    group/aws:
      aws_access_key: "{{ aws_access_key | default(omit) }}"
      aws_secret_key: "{{ aws_secret_key | default(omit) }}"
      security_token: "{{ security_token | default(omit) }}"
      region: "{{ deploy_flask_app_region | default(aws_region) }}"
  block:
    - name: Update ssh_config
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regex: "{{ item.regex }}"
        line: "{{ item.line }}"
      loop:
        - regex: ^(# *)?ClientAliveInterval
          line: ClientAliveInterval  1200
        - regex: ^(# *)?ClientAliveCountMax
          line: ClientAliveCountMax 3
      become: true

    - name: Install required packages
      ansible.builtin.yum:
        name: "{{ deploy_flask_app_bastion_host_required_packages }}"
        state: present
      become: true

    - name: Copy remote ssh private key file into bastion
      ansible.builtin.copy:
        src: "{{ deploy_flask_app_bastion_ssh_private_key }}"
        dest: "{{ deploy_flask_app_workers_ssh_private_key }}"
