---
- name: Clone git repository for web application
  ansible.builtin.git:
    repo: "{{ deploy_flask_app_git_repository }}"
    dest: ~/webapp

- name: Build webapp container image
  ansible.builtin.command:
    cmd: podman build -t webapp .
  args:
    chdir: ~/webapp
  changed_when: false

- name: Check running registry
  ansible.builtin.shell:
    cmd: >
      podman container
      ps -a
      -f name=registry500x
      --format=.Names
  register: deploy_flask_app_container
  become: true
  changed_when: false

- name: Create private registry
  become: true
  when:
    - deploy_flask_app_container.stdout == ""
  block:
    - name: Create folders for the registry
      ansible.builtin.file:
        path: /opt/registry/{{ item }}
        state: directory
        mode: 0644
      with_items:
        - auth
        - certs
        - data

    - name: Generate credentials for accessing the registry
      ansible.builtin.shell:
        cmd: >
          htpasswd -bBc /opt/registry/auth/htpasswd
          {{ deploy_flask_app_local_registry_user }}
          {{ deploy_flask_app_local_registry_pwd }}
      changed_when: false

    - name: Start the registry
      ansible.builtin.shell:
        cmd: >
          podman run --name registry500x
          -p {{ deploy_flask_app_listening_port }}:5000
          -v /opt/registry/data:/var/lib/registry:z
          -v /opt/registry/auth:/auth:z
          -e "REGISTRY_AUTH=htpasswd"
          -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm"
          -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
          -e REGISTRY_COMPATIBILITY_SCHEMA1_ENABLED=true
          -d
          docker.io/library/registry:latest
      changed_when: false

- name: Push image into private registry
  ansible.builtin.shell:
    cmd: >
      podman login 127.0.0.1:{{ deploy_flask_app_listening_port }} -u '{{ deploy_flask_app_local_registry_user }}' -p '{{ deploy_flask_app_local_registry_pwd }}' --tls-verify=false &&
      podman tag webapp 127.0.0.1:{{ deploy_flask_app_listening_port }}/ansible-webapp &&
      podman push 127.0.0.1:{{ deploy_flask_app_listening_port }}/ansible-webapp --tls-verify=false
  changed_when: false
