---
- name: Deploy flask app.
  module_defaults:
    group/aws: "{{ aws_setup_credentials__output }}"
  vars:
    deploy_flask_app__resource_prefix: "{{ deploy_flask_app_vm_info.instances.0.public_dns_name | split('.') | first }}"
    deploy_flask_app__group_id: "{{ deploy_flask_app_vm_info.instances.0.security_groups[0].group_id }}"
    deploy_flask_app__vm_image_id: "{{ deploy_flask_app_vm_info.instances.0.image_id }}"
    deploy_flask_app__bastion_public_ip: "{{ deploy_flask_app_vm_info.instances.0.public_ip_address }}"
    deploy_flask_app__bastion_private_ip: "{{ deploy_flask_app_vm_info.instances.0.private_ip_address }}"
    deploy_flask_app__public_subnet_id: "{{ deploy_flask_app_vm_info.instances.0.subnet_id }}"
    deploy_flask_app__private_subnet_id: "{{ deploy_flask_app_vm_info.instances.0.subnet_id }}"
    deploy_flask_app__rds_host: "{{ deploy_flask_app_rds_info.instances.0.endpoint.address }}"
    deploy_flask_app__rds_dbname: "{{ deploy_flask_app_rds_info.instances.0.db_name }}"
  block:
    - name: Create infrastructure - workers and load balancer
      ansible.builtin.include_tasks: setup_infra.yaml

    - name: Add bastion host to inventory
      ansible.builtin.include_tasks: update_inventory.yaml

    - name: Deploy application into workers
      ansible.builtin.include_tasks: deploy_app.yaml
      with_items: "{{ deploy_flask_app_vms.instances | map(attribute='instance_id') | list }}"
      loop_control:
        loop_var: worker_id
