---
- name: Deploy flask app.
  vars:
    deploy_flask_app__resource_prefix: "{{ deploy_flask_app_vm_info.instances.0.public_dns_name | split('.') | first }}"
    deploy_flask_app__group_id: "{{ deploy_flask_app_vm_info.instances.0.security_groups[0].group_id }}"
    deploy_flask_app__vm_image_id: "{{ deploy_flask_app_vm_info.instances.0.image_id }}"
    deploy_flask_app__bastion_public_ip: "{{ deploy_flask_app_vm_info.instances.0.public_ip_address }}"
    deploy_flask_app__bastion_private_ip: "{{ deploy_flask_app_vm_info.instances.0.private_ip_address }}"
    deploy_flask_app__public_subnet_id: "{{ deploy_flask_app_vm_info.instances.0.subnet_id }}"
    deploy_flask_app__private_subnet_id: "{{ deploy_flask_app_vm_info.instances.0.subnet_id }}"
    deploy_flask_app__rds_host: "{{ deploy_flask_app_rds_info.instances.0.endpoint.address }}"
    deploy_flask_app__rds_dbname: "{{ deploy_flask_app_rds_info.instances.0.db_name }}"
  block:
    - name: Create infrastructure - workers and load balancer
      ansible.builtin.include_tasks: setup_infra.yaml

    - name: Start application container into workers
      ansible.builtin.include_tasks: start_containers.yaml

    - name: Create load balancer
      amazon.aws.elb_classic_lb:
        state: present
        name: "{{ deploy_flask_app__resource_prefix }}-lb"
        listeners:
          - load_balancer_port: "{{ deploy_flask_app_listening_port }}"
            instance_port: 5000
            protocol: HTTP
            instance_protocol: HTTP
        instance_ids: "{{ deploy_flask_app_vms.instances | map(attribute='instance_id') | list }}"
        security_group_ids:
          - "{{ deploy_flask_app__group_id }}"
        subnets:
          - "{{ deploy_flask_app__public_subnet_id }}"
        scheme: internet-facing
        wait: true
        wait_timeout: 600
      register: deploy_flask_app_lb_result

    - name: Display application URL
      ansible.builtin.debug:
        msg: "Application accessible at http://{{ deploy_flask_app_lb_result.elb.dns_name }}:{{ deploy_flask_app_listening_port }}"
