---
- name: Set 'region' variable
  ansible.builtin.set_fact:
    region: "{{ region | default(aws_region) }}"

- name: Create resources playbook
  module_defaults:
    group/aws:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      security_token: "{{ security_token | default(omit) }}"
      region: "{{ region }}"

  block:
    - name: Add host to inventory
      ansible.builtin.add_host:
        hostname: bastion
        ansible_ssh_user: fedora
        ansible_host: "{{ public_ip_address }}"
        ansible_ssh_common_args: -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no -i {{ sshkey_file }}
        ansible_host_name: "{{ public_dns_name | split('.') | first }}"
        host_config:
          public_subnet_id: "{{ public_subnet_id }}"
          private_subnet_id: "{{ private_subnet_id }}"
          image_id: "{{ image_id }}"
          group_id: "{{ secgroup_group_id }}"
          private_ip: "{{ private_ip_address }}"
          vpc_id: "{{ vpc_id }}"
          rds_info:
            host: "{{ endpoint_address }}"
            name: "{{ aws_postgresql_dbname | default('mysampledb123') }}"
            master_user_password: "{{ aws_postgresql_master_password | default('L#5cH2mgy_') }}"
            master_username: "{{ aws_postgresql_master_user | default('ansible') }}"
