---
- name: Update ssh_config
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regex: "{{ item.regex }}"
    line: "{{ item.line }}"
  loop:
    - regex: ^(# *)?ClientAliveInterval
      line: ClientAliveInterval  1200
    - regex: ^(# *)?ClientAliveCountMax
      line: ClientAliveCountMax 3
  become: true

- name: Install required packages
  ansible.builtin.yum:
    name: "{{ deploy_flask_app_bastion_host_required_packages }}"
    state: present
  become: true
  when: deploy_flask_app_bastion_host_required_packages | length > 0

- name: Generate ssh configuration for current user
  ansible.builtin.user:
    generate_ssh_key: true
    state: present
    name: "{{ deploy_flask_app_bastion_host_username }}"

- name: Copy remote ssh private key file into bastion
  ansible.builtin.copy:
    src: "{{ deploy_flask_app_bastion_ssh_private_key }}"
    dest: "{{ deploy_flask_app_workers_ssh_private_key }}"
    mode: 0400
