---
- name: Add bastion host into inventory
  ansible.builtin.add_host:
    hostname: bastion
    ansible_ssh_user: "{{ deploy_flask_app_bastion_host_username }}"
    ansible_host: "{{ deploy_flask_app__bastion_public_ip }}"
    ansible_ssh_common_args: -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no -i {{ deploy_flask_app_bastion_ssh_private_key }}
    ansible_python_interpreter: auto
    ansible_host_name: "{{ deploy_flask_app__resource_prefix }}"
    host_config:
      public_subnet_id: "{{ deploy_flask_app__public_subnet_id }}"
      private_subnet_id: "{{ deploy_flask_app__private_subnet_id }}"
      image_id: "{{ deploy_flask_app__vm_image_id }}"
      group_id: "{{ deploy_flask_app__group_id }}"
      private_ip: "{{ deploy_flask_app__bastion_private_ip }}"
      vpc_id: "{{ deploy_flask_app_vpc_id }}"
      rds_info:
        # host: "{{ deploy_flask_app__rds_host }}"
        # name: "{{ deploy_flask_app__rds_dbname }}"
        master_user_password: "{{ deploy_flask_app_rds_master_password }}"
        master_username: "{{ deploy_flask_app_rds_master_username }}"
