---
# Configure local ssh config
- name: Create ssh configuration files
  ansible.builtin.file:
    state: "{{ item.state }}"
    path: "{{ item.path }}"
  with_items:
    - state: directory
      path: "~/.ssh"
    - state: touch
      path: "~/.ssh/config"

- name: Update local .ssh/config
  ansible.builtin.blockinfile:
    state: present
    insertafter: EOF
    dest: "~/.ssh/config"
    content: "{{ lookup('template', 'ssh_config.j2') }}"

- name: Add bastion host into inventory
  ansible.builtin.add_host:
    hostname: bastion
    ansible_python_interpreter: auto
    ansible_host_name: bastion

- name: Copy remote ssh private key file into bastion
  ansible.builtin.copy:
    src: "{{ deploy_flask_app_bastion_ssh_private_key }}"
    dest: "{{ deploy_flask_app_workers_ssh_private_key }}"
    mode: 0400
  delegate_to: bastion

- name: Add workers into inventory
  ansible.builtin.add_host:
    hostname: "{{ item }}"
    ansible_python_interpreter: auto
    ansible_host_name: "{{ item }}"
  with_items: "{{ deploy_flask_app_vms.instances | map(attribute='instance_id') | list }}"
