---
- name: Get instance info with provided name
  amazon.aws.ec2_instance_info:
    filters:
      tag:Name: "{{ ec2_instance_create_delete_instance_name }}"
      instance-state-name: ["pending", "running", "stopping", "stopped"]
  register: ec2_info_result

- name: Disassociate and release EIP if present
  when: ec2_info_result.instances | length > 0
  # and ec2_info_result.instances[0].network_interfaces.association.public_ip is defined
  amazon.aws.ec2_eip:
    device_id: "{{ ec2_info_result.instances[0].instance_id }}"
    state: absent
    release_on_disassociation: true

- name: Terminate EC2 Instance if present
  when: ec2_info_result.instances | length > 0
  amazon.aws.ec2_instance:
    state: terminated
    wait: "{{ ec2_instance_create_delete_wait_for_state }}"
    instance_ids:
      - "{{ ec2_info_result.instances[0].instance_id }}"
