---
backup_select_resources_all_resources: "*"
backup_select_resources_all_s3_buckets: "arn:aws:s3:::*"
backup_select_resources_all_rds_db_instances: "arn:aws:rds:*:*:db:*"

backup_select_resources_tag_list_backup_or_prod:  # Resources tagged {"backup": "true"} OR {"env": "prod"}
  - condition_type: "STRINGEQUALS"
    condition_key: "backup"
    condition_value: "true"
  - condition_type: "StringEquals"
    condition_key: "env"
    condition_value: "prod"

backup_select_resources_conditions_tagged_backup_and_prod:  # Resources tagged {"backup": "true"} AND {"env": "prod"}
  string_equals:
    - condition_key: "aws:ResourceTag/backup"
      condition_value: "true"
    - condition_key: "aws:ResourceTag/env"
      condition_value: "prod"
