---
argument_specs:
  main:
    version_added: 2.0.0
    short_description: A role that imports a local .raw image into an Amazon Machine Image (AMI) and run an AWS EC2 instance.
    description:
      - A role that imports a local .raw image into an Amazon Machine Image (AMI) and run an AWS EC2 instance.
    options:
      import_image_and_run_aws_instance_import_image_task_name:
        description:
          - The name you want to assign to the AWS EC2 import image task.
        required: true
        type: str
      import_image_and_run_aws_instance_bucket_name:
        description:
          - The name of the S3 bucket name where you want to upload the .raw image.
        required: true
        type: str
      import_image_and_run_aws_instance_image_path:
        description:
          - The path where the .raw image is stored.
        default: ""
      import_image_and_run_aws_instance_instance_name:
        description:
          - The name of the EC2 instance you want to create using the imported AMI.
        required: true
      import_image_and_run_aws_instance_instance_type:
        description:
          - The EC2 instance type you want to use.
        default: "t2.micro"
      import_image_and_run_aws_instances_keypair_name:
        description:
          - The name of the SSH access key to assign to the EC2 instance. It must exist in the region the instance is created.
          - If not set, your default AWS account keypair will be used.
      import_image_and_run_aws_instance_security_groups:
        description:
          - A list of security group IDs or names to associate to the EC2 instance.
        type: list
        elements: str
      import_image_and_run_aws_instance_vpc_subnet_id:
        description:
          - The subnet ID in which to launch the EC2 instance (VPC).
          - If none is provided, M(amazon.aws.ec2_instance) will choose the default zone of the default VPC.
      import_image_and_run_aws_instance_volumes:
        description:
          - A dictionary of a block device mappings, by default this will always use the AMI root device so the **instance_volumes** option is primarily for adding more storage.
        type: dict
        options:
          device_name:
            description:
              - The device name (for example, /dev/sdh or xvdh).
          ebs:
            description:
              - Parameters used to automatically set up EBS volumes when the instance is launched.
            type: dict
            options:
              volume_type:
                description:
                  - The volume type.
                  - "Valid Values: standard, io1, io2, gp2, sc1, st1, gp3."
              volume_size:
                description:
                  - The size of the volume, in GiBs.
                type: int
              kms_key_id:
                description:
                  - Identifier (key ID, key alias, ID ARN, or alias ARN) for a customer managed CMK under which the EBS volume is encrypted.
              iops:
                description:
                  - The number of I/O operations per second (IOPS). For gp3, io1, and io2 volumes, this represents the number of IOPS that are provisioned for the volume. For gp2 volumes, this represents the baseline performance of the volume and the rate at which the volume accumulates I/O credits for bursting.
              delete_on_termination:
                description:
                  - Indicates whether the EBS volume is deleted on instance termination.
                type: bool
