---
- name: Fail when unexpected value for operation is provided
  ansible.builtin.fail:
    msg: Unexpected value for awsconfig_multiregion_cloudtrail_operation, should be one of 'create' or 'delete'
  when: awsconfig_multiregion_cloudtrail_operation not in ['create', 'delete']

- name: Fail when 'awsconfig_multiregion_cloudtrail_trail_name' is not defined
  ansible.builtin.fail:
    msg: Cloud trail name must be defined using variable trail_name
  when: awsconfig_multiregion_cloudtrail_trail_name is undefined

- name: Fail when 'awsconfig_multiregion_cloudtrail_bucket_name' is not defined
  ansible.builtin.fail:
    msg: Bucket name must be defined using variable awsconfig_multiregion_cloudtrail_bucket_name
  when:
    - awsconfig_multiregion_cloudtrail_operation == 'create'
    - awsconfig_multiregion_cloudtrail_bucket_name is undefined

- name: Run 'awsconfig_multiregion_cloudtrail' role
  module_defaults:
    group/aws: "{{ aws_setup_credentials__output }}"

  block:
    - name: Create Cloud trail and start logging or Delete existing Cloud trail
      amazon.aws.cloudtrail:
        state: "{{ (awsconfig_multiregion_cloudtrail_operation == 'create') | ternary('present', 'absent') }}"
        name: "{{ awsconfig_multiregion_cloudtrail_trail_name }}"
        enable_logging: true
        s3_bucket_name: "{{ awsconfig_multiregion_cloudtrail_bucket_name | default(omit) }}"
        s3_key_prefix: "{{ awsconfig_multiregion_cloudtrail_key_prefix | default(omit) }}"
        is_multi_region_trail: true
      register: awsconfig_multiregion_cloudtrail_result

    - name: Create/update trail
      when: awsconfig_multiregion_cloudtrail_operation == 'create'
      block:
        - name: Verify that trail has been created/updated
          ansible.builtin.debug:
            msg: Trail '{{ awsconfig_multiregion_cloudtrail_trail_name }}' successfully created/updated.
          when: awsconfig_multiregion_cloudtrail_result is changed

        - name: Verify that trail already exists
          ansible.builtin.debug:
            msg: Trail '{{ awsconfig_multiregion_cloudtrail_trail_name }}' already exists.
          when: awsconfig_multiregion_cloudtrail_result is not changed

    - name: Delete trail
      when: awsconfig_multiregion_cloudtrail_operation == 'delete'
      block:
        - name: Verify that trail has been deleted
          ansible.builtin.debug:
            msg: Trail '{{ awsconfig_multiregion_cloudtrail_trail_name }}' successfully deleted.
          when: awsconfig_multiregion_cloudtrail_result is changed

        - name: Verify that trail does not exists anymore
          ansible.builtin.debug:
            msg: Trail '{{ awsconfig_multiregion_cloudtrail_trail_name }}' does not exist.
          when: awsconfig_multiregion_cloudtrail_result is not changed
