---
- name: Create necessary network resources
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get list of internal sg rules
      ansible.builtin.set_fact:
        sg_rules: "{{ security_group_rules | split(';') | list }}"

    - name: Set default value for the security group rules if nothing is passed.
      ansible.builtin.set_fact:
        sg_internal_rules: "{{ sg_rules | default([
          {'proto': 'tcp', 'port': '22', 'cidr_ip': vpc_cidr}
        ]) }}"

    - name: Configure Network resources
      ansible.builtin.include_role:
        name: cloud.aws_ops.ec2_networking_resources
      vars:
        aws_region: "{{ region }}"
        ec2_networking_resources_vpc_name: "{{ vpc_name }}"
        ec2_networking_resources_vpc_cidr_block: "{{ vpc_cidr }}"
        ec2_networking_resources_subnet_cidr_block: "{{ subnet }}"
        ec2_networking_resources_sg_internal_name: "{{ security_group_internal_name }}"
        ec2_networking_resources_sg_internal_description: "{{ security_group_internal_description }}"
        ec2_networking_resources_sg_internal_rules: "{{ sg_internal_rules }}"
