---
- name: Install required packages
  when: customized_ami_packages is defined
  become: true
  delegate_to: ec2
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ customized_ami_packages }}"

- name: Create custom AMI from instance id
  amazon.aws.ec2_ami:
    instance_id: "{{ customized_ami__instance_id }}"
    name: "{{ customized_ami_name }}"
    wait: true
    state: present
