---
- name: Fail when 'customized_ami_name' is not defined
  ansible.builtin.fail:
    msg: Custom AMI name should be defined using variable customized_ami_name
  when: customized_ami_name is undefined

- name: Run 'customized_ami' role
  module_defaults:
    group/aws: "{{ aws_setup_credentials__output }}"

  block:
    - name: Include file
      ansible.builtin.include_tasks: "{{ customized_ami_operation }}.yaml"
