---
- name: Webapp
  hosts: localhost
  gather_facts: false

  vars_files:
    - vars/main.yaml

  tasks:
    - name: Fail when 'resource_prefix' is not defined
      ansible.builtin.fail:
        msg: resource prefix should be defined as resource_prefix
      when: resource_prefix is not defined

    - name: Run operation create/delete
      ansible.builtin.import_tasks: tasks/{{ operation }}.yaml

- name: Deploy resource from Bastion
  hosts: localhost
  gather_facts: false

  vars_files:
    - vars/main.yaml

  tasks:
    - name: Deploy app
      when: operation == "create"
      ansible.builtin.include_role:
        name: cloud.aws_ops.deploy_flask_app
      vars:
        private_subnet_id: "{{ private_subnet.subnet.id }}"
        vpc_id: "{{ vpc.vpc.id }}"
        vm_info: "{{ vm_result }}"
        rds_info: "{{ rds_result }}"
